eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA:http://localhost:8761/eureka/}

server:
  port: ${PORT:8888}

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/anvigudach/configuration
